name: Deploy to AWS

on:
  push:
    branches:
      - main  # O pipeline será executado na branch main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Baixar o código do repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # Passo 2: Configurar o Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' # Certifique-se de usar a versão do Node.js compatível com o seu NestJS

      # Passo 3: Instalar dependências
      - name: Install dependencies
        run: npm install

      # Passo 4: Build do projeto
      - name: Build project
        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checkout código novamente no job de deploy
      - name: Checkout code
        uses: actions/checkout@v3

      # Passo 2: AWS CLI para autenticação
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # ou outra região preferida

      # Passo 3: Deploy para AWS
      # Este exemplo é de um container no ECS (ajuste conforme sua estratégia)
      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster my-cluster \
            --service my-service \
            --force-new-deployment